# This filegroup makes the SoyToJsSrcCompiler.jar available for use by the
# soy_library Bazel macro.
filegroup(
    name = "soy_js_compiler",
    srcs = ["SoyToJsSrcCompiler.jar"],
    visibility = ["//visibility:public"],
)
